# Generated by Django 3.1.7 on 2021-02-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='navitem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
