# Generated by Django 3.1.7 on 2021-02-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_site', '0002_auto_20210219_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='location',
            new_name='url',
        ),
    ]
